"""kobi.demo — hear every GM program straight from the uncompressed sources.

For each program the first ingestible candidate is turned into a temporary SFZ (its default view:
one keyswitch, attack triggers, controller gates at their defaults) and a short phrase is rendered
with sfizz: an arpeggio and a chord in the instrument's own range, hits for one-shots, a beat for
the drum kit.  Each phrase is peak-normalised so sources of very different level are comparable,
then everything is joined into one file with a cue sheet.

    python3 -m kobi.demo                 # all programs + drums -> demo/kobi_demo_uncompressed.wav, demo/CUES.md
    python3 -m kobi.demo 0 56 118        # a few programs, printed timings
"""
from __future__ import annotations

import os
import re
import sys
import time

import numpy as np
import soundfile as sf

from .gm_map import DRUMS, PROGRAMS
from .ingest import Instrument, default_view, load_candidate, _cc_default, _groupby, _MICS, _num
from . import paths

FS = 44100
BLOCK = 1024
GAP_S = 0.6
_ENV = ('ampeg_attack', 'ampeg_hold', 'ampeg_decay', 'ampeg_sustain', 'ampeg_release')
_COPY = ('amp_veltrack', 'pitch_keytrack', 'offset', 'end', 'rt_decay', 'amp_velcurve_1', 'amp_velcurve_127')
_CC_MOD = re.compile(r'^(ampeg_(?:attack|hold|decay|sustain|release))_(?:on)?cc(\d+)$')


def _resolved_envelope(r, control: dict) -> dict:
    """Envelope opcodes with their controller modulations applied at the file's default CC values
    (Karoryfer writes ampeg_sustain=0 ampeg_sustain_oncc103=100 with set_cc103=127: sustain is 100)."""
    env = {k: _num(r.opcodes[k], 0.0) for k in _ENV if k in r.opcodes}
    for k, v in r.opcodes.items():
        m = _CC_MOD.match(k)
        if m:
            base, cc = m.group(1), int(m.group(2))
            env[base] = env.get(base, 0.0) + _num(v, 0.0) * _cc_default(cc, control) / 127.0
    return env


def write_view_sfz(inst: Instrument, view: list, path: str, kind: str) -> dict:
    """Write the regions of ``view`` as a plain SFZ.  Keyless one-shots get one key per articulation
    group from 60 upward.  Returns {'keys': sorted playable keys, 'lo': lowest key, 'hi': highest}."""
    lines = ['// generated by kobi.demo from ' + inst.origin, f'<global> ampeg_release={"0.05" if kind in ("oneshot", "kit") else "0.35"}']
    keyless = [r for r in view if r.pitch_keycenter is None]
    groups = _groupby(keyless, lambda r: tuple(t for t in r.tags if t not in _MICS))
    keymap = {g: 60 + i for i, g in enumerate(groups)}
    keys = set()
    for r in view:
        if r.pitch_keycenter is None:
            k = keymap[tuple(t for t in r.tags if t not in _MICS)]
            lo, hi, kc, extra = k, k, k, ' pitch_keytrack=0'
        else:
            lo, hi, kc, extra = r.lokey, r.hikey, r.pitch_keycenter, ''
        keys.update(range(lo, hi + 1))
        op = [f'<region> sample={r.sample}', f'lokey={lo} hikey={hi} pitch_keycenter={kc} lovel={r.lovel} hivel={r.hivel}' + extra]
        if abs(r.tune) > 0.01:
            op.append(f'tune={r.tune:g}')
        if abs(r.volume_db) > 0.01:
            op.append(f'volume={r.volume_db:g}')
        if abs(r.pan) > 0.01:
            op.append(f'pan={r.pan:g}')
        if r.loop_end is not None and r.loop_mode not in ('no_loop', 'one_shot'):
            op.append(f'loop_mode={r.loop_mode or "loop_continuous"} loop_start={r.loop_start or 0} loop_end={r.loop_end}')
        elif kind in ('oneshot', 'kit'):
            op.append('loop_mode=one_shot')            # play the whole hit regardless of note-off
        elif r.loop_mode in ('no_loop', 'one_shot'):
            op.append(f'loop_mode={r.loop_mode}')
        if r.seq_length > 1:
            op.append(f'seq_length={r.seq_length} seq_position={r.seq_position}')
        if r.lorand > 0 or r.hirand < 1:
            op.append(f'lorand={r.lorand:g} hirand={r.hirand:g}')
        for k in _COPY:
            if k in r.opcodes:
                op.append(f'{k}={r.opcodes[k]}')
        for k, v in _resolved_envelope(r, inst.control).items():
            op.append(f'{k}={v:g}')
        lines.append(' '.join(op))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')
    ks = sorted(keys)
    return dict(keys=ks, lo=ks[0] if ks else 60, hi=ks[-1] if ks else 60, centres=sorted({r.pitch_keycenter for r in view if r.pitch_keycenter is not None}))


def phrase(kind: str, info: dict) -> tuple[list, float]:
    """[(time_s, 'on'|'off', key, vel)] and the total length in seconds."""
    ev = []
    if kind == 'kit':
        # GM drum pattern, 120 bpm, two bars
        hits = [(0.0, 49, 110)]
        for bar in range(2):
            t0 = bar * 2.0
            for beat in range(4):
                t = t0 + beat * 0.5
                hits.append((t, 36, 112) if beat in (0, 2) else (t, 38, 105))
                hits += [(t, 42, 90), (t + 0.25, 42, 70)]
            hits += [(t0 + 1.75, 36, 100)]
        for t, k, v in hits:
            ev += [(t, 'on', k, v), (t + 0.1, 'off', k, 0)]
        return ev, 4.6
    if kind == 'oneshot' or not info['centres']:
        keys = info['keys'][:8] if len(info['keys']) <= 16 else info['keys'][::max(1, len(info['keys']) // 8)][:8]
        for i, k in enumerate(keys):
            ev += [(i * 0.4, 'on', k, 100), (i * 0.4 + 0.2, 'off', k, 0)]
        return ev, len(keys) * 0.4 + 1.6
    lo, hi = info['lo'], info['hi']
    c = info['centres']
    root = c[len(c) // 2]
    if root + 12 > hi:
        root = max(lo, hi - 12)
    notes = [min(hi, max(lo, root + d)) for d in (0, 4, 7, 12)]
    for i, k in enumerate(notes):
        t = i * 0.5
        ev += [(t, 'on', k, 96), (t + 0.48, 'off', k, 0)]
    for k in notes:
        ev += [(2.2, 'on', k, 110), (3.9, 'off', k, 0)]
    return ev, 5.2 if kind == 'sustain' else 5.6


def render(sfz_path: str, events: list, seconds: float) -> np.ndarray:
    import pysfizz
    synth = pysfizz.Synth(sample_rate=FS)
    synth.set_block_size(BLOCK)
    if not synth._synth.load_sfz_file(sfz_path):
        raise RuntimeError(f'sfizz refused {sfz_path}')
    # offline: load sample data synchronously.  Otherwise sfizz streams past its preload in a background
    # thread, and on a busy machine a note deep in a packed Ogg can start before its audio has arrived
    # (seen as a key measuring 12 dB low, or a wrong pitch, only when renders ran 18 at a time)
    synth._synth.enable_freewheeling()
    events = sorted(events, key=lambda e: (e[0], e[1] == 'on'))
    n = int(seconds * FS)
    out = np.zeros((n + BLOCK, 2), dtype=np.float32)
    ei, pos = 0, 0
    while pos < n:
        while ei < len(events) and int(events[ei][0] * FS) < pos + BLOCK:
            t, typ, key, vel = events[ei]
            d = max(0, int(t * FS) - pos)
            if typ == 'on':
                synth._synth.note_on(d, key, vel)
            else:
                synth._synth.note_off(d, key, 0)
            ei += 1
        left, right = synth._synth.render_block()
        out[pos:pos + BLOCK, 0] = left
        out[pos:pos + BLOCK, 1] = right
        pos += BLOCK
    return out[:n]


def normalise(x: np.ndarray, peak_db: float = -3.0) -> tuple[np.ndarray, float]:
    peak = float(np.max(np.abs(x))) if len(x) else 0.0
    if peak < 1e-5:
        return x, -np.inf
    return x * (10 ** (peak_db / 20) / peak), 20 * np.log10(peak)


def demo_program(num, name: str, cands: list, out_dir: str, kind_override: str | None = None, bank_gains: str | None = None) -> dict | None:
    for c in cands:
        inst = load_candidate(c, name)
        if inst is None:
            continue
        view = default_view(inst)
        if not view:
            continue
        kind = kind_override or c.kind
        tag = f'{num:03d}' if isinstance(num, int) else str(num)
        stem = f"{tag}_{name.replace(' ', '_').replace('/', '-')}"
        sfz = os.path.join(out_dir, 'sfz', stem + '.sfz')
        info = write_view_sfz(inst, view, sfz, kind)
        if bank_gains:
            import glob, re as _re
            from .levels import apply_gain
            hit = glob.glob(os.path.join(bank_gains, ('Drums' if tag == 'drums' else tag + ' *') + '.sfz'))
            if hit:
                with open(hit[0]) as fh:
                    m = _re.search(r'<global>.*?volume=(-?[\d.]+)', fh.read())
                if m:
                    apply_gain(sfz, float(m.group(1)))
        ev, secs = phrase(kind, info)
        t0 = time.time()
        audio = render(sfz, ev, secs)
        if bank_gains:
            src_peak_db = 20 * np.log10(float(np.max(np.abs(audio))) + 1e-9)
            if np.max(np.abs(audio)) > 0.99:
                audio = audio * (0.99 / float(np.max(np.abs(audio))))
        else:
            audio, src_peak_db = normalise(audio)
        wav = os.path.join(out_dir, 'programs', stem + '.wav')
        os.makedirs(os.path.dirname(wav), exist_ok=True)
        sf.write(wav, audio, FS, subtype='PCM_16')
        return dict(num=num, name=name, cand=f'{c.source}: {c.path}' + (f' [{c.sub}]' if c.sub and c.source != 'FreePats' else ''),
                    kind=kind, regions=len(view), audio=audio, wav=wav, src_peak_db=src_peak_db, render_s=time.time() - t0,
                    standin=c.standin)
    return None


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    out_dir = os.path.join(paths.ROOT, 'demo')
    if '-o' in argv:
        i = argv.index('-o')
        out_dir = argv[i + 1]
        argv = argv[:i] + argv[i + 2:]
    bank_gains = None
    if '--bank-gains' in argv:                     # take <global> volume= from the levelled bank, skip normalisation
        i = argv.index('--bank-gains')
        bank_gains = argv[i + 1]
        argv = argv[:i] + argv[i + 2:]
    drums_sfz = None
    if '--drums' in argv:                          # a ready GM kit (kobi.drums) instead of the raw source kits
        i = argv.index('--drums')
        drums_sfz = argv[i + 1]
        argv = argv[:i] + argv[i + 2:]
    nums = [int(a) for a in argv if a.isdigit()]
    todo = [(p.num, p.name, p.cands, None) for p in PROGRAMS if not nums or p.num in nums]
    if not nums:
        todo.append(('drums', 'Drum kit', DRUMS, 'kit'))
    parts, cues, t = [], [], 0.0
    gap = np.zeros((int(GAP_S * FS), 2), dtype=np.float32)
    for num, name, cands, kind in todo:
        try:
            if num == 'drums' and drums_sfz:
                ev, secs = phrase('kit', {})
                audio = render(drums_sfz, ev, secs)
                pk = float(np.max(np.abs(audio)))
                r = dict(num=num, name=name, cand='kobi.drums GM kit', kind='kit', regions=sum(1 for l in open(drums_sfz) if l.startswith('<region>')),
                         audio=audio * (0.99 / pk if pk > 0.99 else 1.0), src_peak_db=20 * np.log10(pk + 1e-9), render_s=0.0, standin=False)
                wav = os.path.join(out_dir, 'programs', 'drums_GM_kit.wav')
                os.makedirs(os.path.dirname(wav), exist_ok=True)
                sf.write(wav, r['audio'], FS, subtype='PCM_16')
            else:
                r = demo_program(num, name, cands, out_dir, kind, bank_gains)
        except Exception as e:                                   # keep going, report in the cue sheet
            r = None
            print(f'{str(num):>5} {name:26s} FAILED: {e}', flush=True)
            cues.append(dict(num=num, name=name, t=t, cand='FAILED: ' + str(e)[:80], kind='', regions=0, src_peak_db=-np.inf, standin=False))
            continue
        if r is None:
            print(f'{str(num):>5} {name:26s} nothing to render', flush=True)
            cues.append(dict(num=num, name=name, t=t, cand='(no candidate)', kind='', regions=0, src_peak_db=-np.inf, standin=False))
            continue
        cues.append(dict(**{k: r[k] for k in ('num', 'name', 'cand', 'kind', 'regions', 'src_peak_db', 'standin')}, t=t))
        print(f"{str(num):>5} {name:26s} {r['kind']:8s} {r['regions']:5d} regions  src peak {r['src_peak_db']:6.1f} dB  "
              f"at {int(t // 60):d}:{t % 60:04.1f}  ({r['render_s']:.1f}s)", flush=True)
        parts += [r['audio'], gap]
        t += len(r['audio']) / FS + GAP_S
    if not parts:
        return 1
    full = np.concatenate(parts)
    os.makedirs(out_dir, exist_ok=True)
    name = ('kobi_demo_levelled.wav' if bank_gains else 'kobi_demo_uncompressed.wav') if not nums else 'kobi_demo_selection.wav'
    sf.write(os.path.join(out_dir, name), full, FS, subtype='PCM_16')
    lines = ['# Demo cue sheet', '', f'`{name}`: {len(full) / FS / 60:.1f} min, {FS / 1000:g} kHz 16-bit stereo, rendered by sfizz from '
             'the uncompressed sources through the default view of each program\'s first candidate; each phrase peak-normalised '
             'to -3 dBFS (src peak = the level the raw render had).  Per-program files in `programs/`, the SFZs used in `sfz/`.', '',
             '| time | # | program | source | kind | regions | src peak dB | stand-in |', '|---|---|---|---|---|---|---|---|']
    for c in cues:
        lines.append(f"| {int(c['t'] // 60)}:{c['t'] % 60:04.1f} | {c['num']} | {c['name']} | {c['cand']} | {c['kind']} | {c['regions']} | "
                     f"{'silent' if c['src_peak_db'] == -np.inf else format(c['src_peak_db'], '.1f')} | {'yes' if c['standin'] else ''} |")
    with open(os.path.join(out_dir, 'CUES.md'), 'w') as fh:
        fh.write('\n'.join(lines) + '\n')
    print(f'wrote {os.path.join(out_dir, name)} ({len(full) / FS / 60:.1f} min) and CUES.md')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
